from io import StringIO

class Preprocessor:
    line_directive: str | None = "#line"

    def __init__(self) -> None: ...
    def parse(self, input, source: str | None = None, ignore: dict = {}): ...
    def write(self, io: StringIO): ...
