name: CI

# Events that trigger workflow
on:
  push:
    branches:
      - "main"
  pull_request:

concurrency:
  # Behavior:
  # - Group all pull requests: latest push cancels previous ones
  # - Group all branches:
  #   - If main/version- branches: run serially
  #   - Else, latest push cancels previous ones
  group: >
    ${{
      (github.event_name == 'pull_request' && format('pr-{0}', github.event.pull_request.number)) ||
      (github.event_name == 'push' && format('branch-{0}', github.ref_name)) ||
      ''
    }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  lint:
    name: Lint Python Code
    runs-on: ubuntu-24.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7
      - name: Install Linters
        run: make venv
      - name: Lint
        run: make lint
  build:
    name: Build
    runs-on: ubuntu-24.04
    needs: lint
    steps:
      - name: Check Git repository
        uses: actions/checkout@v7
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - name: Build Distribution
        run: |
          make dist
      - uses: actions/upload-artifact@v7
        with:
          name: wheel
          path: ./dist
  test:
    name: Test
    runs-on: ubuntu-24.04
    needs: build
    steps:
      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"
      - uses: actions/download-artifact@v8
        with:
          name: wheel
          path: ./dist
      - name: Install Ciel, jq
        run: |
          sudo apt-get install -y jq
          pip3 install ./dist/ciel-*.whl
      - name: Ensure PDK downloads work
        shell: bash
        run: |
          for pdk in $(python3 -m ciel ls-pdks | jq -r 'keys[]' | tr '\n' ' '); do
            version="$(python3 -m ciel ls-remote --pdk $pdk | head -n1)"
            python3 -m ciel fetch --pdk $pdk $version
            python3 -m ciel prune --pdk $pdk --yes
          done
  check_new_version:
    name: Check for new version in pyproject.toml
    runs-on: ubuntu-24.04
    if: github.event_name == 'push' && github.ref_name == 'main'
    outputs:
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - id: get_version
        name: Extract new version
        run: |
          VERSION="$(perl -ne 'print $1 if /^version\s*=\s*\"(.+?)\"/' pyproject.toml)"
          if ! gh release view $VERSION 2>&1 > /dev/null; then
            echo "Uploading new version $VERSION if CI passes."
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          fi
  publish:
    name: Publish
    runs-on: ubuntu-24.04
    needs: [lint, build, test, check_new_version]
    if: needs.check_new_version.outputs.version != ''
    environment: pypi
    permissions:
      # IMPORTANT: this permission is mandatory for Trusted Publishing
      id-token: write
      contents: write
    steps:
      - uses: actions/download-artifact@v8
        with:
          name: wheel
          path: ./dist
      # 2nd to last because it is immutable but likely to fail, so if it fails
      # I don't want PyPI publishing
      - name: Create release
        run: |
          prerelease_arg=()
          version="${{ needs.check_new_version.outputs.version }}"
          if [[ "$version" = *b* ]] || [[ "$version" = *a* ]] || [[ "$version" = *.dev* ]] || [[ "$version" = *rc* ]]; then
            prerelease_arg+=( "--prerelease" )
          fi

          gh release create $version \
            --generate-notes \
            --target "${{ github.ref_name }}" \
            "${prerelease_arg[@]}" \
            ./dist/*
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
